[package]
name = "vinci_java"
version = "0.0.1"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vinci_java"

[dependencies]
vinci_core = { path = "../vinci_core" }