language: rust

rust:
  - stable
  - nightly
  - beta
    
matrix:
  allow_failures:
    - rust: nightly
  
jobs:
  fast_finish: true
  
cache: cargo

apt: true

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      
before_cache: |
    cargo install cargo-tarpaulin
      
after_success: |
        taskset -c 0 cargo tarpaulin --out Xml --all --all-features
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage"
