[package]
name = "vinci_vcs"
version = "0.0.1"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vinci_vcs"

[dependencies]
libgit2-sys = "0.9.1"